### ISSUE TITLE
Which is the license of this project?

### ISSUE THREAD

**Issue by rbejar** [GeoscienceAustralia/dggs-pilot#1]
There is no LICENSE file in the repository. Is it FOSS? If so, with which license?

Thanks!

**Comment by Kirill888** [comment]
@rbejar this prototype is meant to be open source, my omission for not putting exact license, I'll check what license GA is usually using and will push it into this repo, probably Apache, but I need to confirm.

**Comment by Kirill888** [comment]
I have added Apache 2.0 license, thanks for pointing out lack of license.

**Comment by rbejar** [comment]
:+1:
